#!/bin/sh

get_date_status() {
        echo "$(date +"%a %e/%m/%y | %T")"
}

get_ram_status() {
        free | grep '^Mem' | awk '{print $3}'
}

get_cpu_status() {
        top -n 1 -b | awk '/^%Cpu/{print " " $2 "%"}'
}

get_battery_status() {
        # (cat /sys/class/power_supply/BAT0/status | grep "Charging" > /dev/null 2>&1) &&
        # 	echo -n " " ||
        # 	echo -n " ";
        echo "$(apm -l)%"
}

get_cpu_freq_status() {
        apm | tail -n1 | sed 's/.*(//g;s/).*//g'
}

get_cpu_temp_status() {
        sysctl -n hw.sensors.cpu0.temp0 | cut -d' ' -f1
}

date_status="$(get_date_status)"
ram_status="$(get_ram_status)"
# cpu_status="$(get_cpu_status)"
battery_status="$(get_battery_status)"
cpu_temp_status="$(get_cpu_temp_status)"
cpu_freq_status="$(get_cpu_freq_status)"

_bar_secs='-1';
while true; do
        _bar_secs="$(((_bar_secs+1)%5))";

        date_status="$(get_date_status)"
        cpu_temp_status="$(get_cpu_temp_status)"
        if [ "$_bar_secs" -eq 0 ]; then
            ram_status="$(get_ram_status)"
            # cpu_status="$(get_cpu_status)"
            battery_status="$(get_battery_status)"
            cpu_freq_status="$(get_cpu_freq_status)"
        fi

        # name="   $battery_status   $cpu_temp_status  $cpu_status   $ram_status   $date_status"
        name="   $battery_status | $cpu_temp_status ($cpu_freq_status) | $ram_status | $date_status"

        xsetroot -name "$name";
        sleep 1;
done
