#!/bin/sh

SOLUTION_EXTENSION=".cpp";

cache_dir="/tmp/codeforces/cv/$1";
mkdir -p "$cache_dir";

sol_name="$1$SOLUTION_EXTENSION"

diff "$sol_name" "$cache_dir/$sol_name" >/dev/null 2>&1;
if [ "$?" = "0" ]; then
    echo -e "compiled before...\n" 1>&2;
    $cache_dir/$1;
else
    g++ -std=c++17 -Wall "$sol_name" -o "$cache_dir/$1" -D thud_local -fsanitize=address -fsanitize=undefined &&
        echo -e "built successfully...\n" 1>&2 &&
        cp "$sol_name" "$cache_dir/$sol_name" &&
        $cache_dir/$1;
fi
