#!/bin/sh

wallpapers="$(ls "$XDG_CONFIG_HOME/wallpapers")";
nwallpapers="$(echo "$wallpapers" | wc -l)";

chosen="$(echo "$wallpapers" | awk "NR==$((RANDOM%nwallpapers+1))")";

cp "$XDG_CONFIG_HOME/wallpapers/$chosen" "$XDG_CONFIG_HOME/wall"

xwallpaper --zoom "$XDG_CONFIG_HOME/wall"
