#!/bin/sh

xset r rate 350 50
echo "set key rehit speed..."
picom -b --config ~/.picom.conf;
echo "started picom...";
setbg;
echo "set wallpaper...";
xinput --set-prop "Elan Touchpad" "libinput Tapping Enabled" 1;
echo "enabled touchpad tapping...";
